Resources:
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "accounts"

  StoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "storeId"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "categories"
          AttributeType: "L"
      KeySchema:
        - AttributeName: "storeId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "stores"
      GlobalSecondaryIndexes:
        - IndexName: "StoreNameIndex"
          KeySchema:
            - AttributeName: "name"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "StoreCategoryIndex"
          KeySchema:
            - AttributeName: "categories"
              KeyType: "HASH"
            - AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "itemId"
          AttributeType: "S"
        - AttributeName: "storeId"
          AttributeType: "S"
        KeySchema:
          - AttributeName: "itemId"
            KeyType: "HASH"
          - AttributeName: "storeId"
            KeyType: "RANGE"
        BillingMode: "PAY_PER_REQUEST"
        TableName: "items"
